version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./reservations.json:/app/reservations.json
    environment:
      PORT: ${PORT:-3001}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    restart: unless-stopped
